version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - '8080:8080'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/database
    volumes:
      - type: bind
        source: ./server/src
        target: /app/src
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - type: bind
        source: ./client/src
        target: /app/src
      - type: bind
        source: ./client/public
        target: /app/public
    depends_on:
      - server
    command: npm run dev
      
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: