version: '3'
services:
  server:
    env_file: .env
    build:
      context: ./server
      dockerfile: DockerFile
    expose:
      - '8080'

  client:
    env_file: .env
    build:
      context: ./client
      dockerfile: DockerFile
    ports:
      - '3000:3000'
    depends_on:
      - server

volumes:
  server: