version: '3.8'
services:
  server:
    container_name: ${SERVER_HOST}
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - mongo
    # environment:
    #   - MONGO_URI=mongodb://mongo:27017/database
    volumes:
      - type: bind
        source: ./server/src
        target: /app/src
    command: npm run dev

  client:
    container_name: ${CLIENT_HOST}
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - type: bind
        source: ./client/src
        target: /app/src
      - type: bind
        source: ./client/public
        target: /app/public
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
    depends_on:
      - server
    command: npm run dev
      
  mongo:
    container_name: ${MONGO_HOST}
    env_file: .env
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    name: "mongodata"