version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: DockerFile
    expose:
      - '8080:8080'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/database

  client:
    build:
      context: ./client
      dockerfile: DockerFile
    ports:
      - '3000:3000'
    depends_on:
      - server
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: